# Generated by Django 4.2.8 on 2023-12-17 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='publication_date',
            field=models.DateTimeField(verbose_name=datetime.datetime),
        ),
    ]
